# Generated by Django 6.1.1 on 2026-09-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Khata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('JOMA', 'Income'), ('KHOROCH', 'Expense')], max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
