# Generated by Django 6.1.1 on 2026-09-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hisab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khata',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10),
        ),
    ]
